#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AreaMap_TopMenu_Cell

#include "Basic.hpp"

#include "AreaMap_TopMenu_Cell_classes.hpp"
#include "AreaMap_TopMenu_Cell_parameters.hpp"


namespace SDK
{

// Function AreaMap_TopMenu_Cell.AreaMap_TopMenu_Cell_C.ExecuteUbergraph_AreaMap_TopMenu_Cell
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAreaMap_TopMenu_Cell_C::ExecuteUbergraph_AreaMap_TopMenu_Cell(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AreaMap_TopMenu_Cell_C", "ExecuteUbergraph_AreaMap_TopMenu_Cell");

	Params::AreaMap_TopMenu_Cell_C_ExecuteUbergraph_AreaMap_TopMenu_Cell Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AreaMap_TopMenu_Cell.AreaMap_TopMenu_Cell_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAreaMap_TopMenu_Cell_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AreaMap_TopMenu_Cell_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

