#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BG0029_00_Door1Knob_Standard

#include "Basic.hpp"

#include "BG9010_00_Door1Knob_Standard_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BG0029_00_Door1Knob_Standard.BG0029_00_Door1Knob_Standard_C
// 0x0000 (0x0810 - 0x0810)
class ABG0029_00_Door1Knob_Standard_C final : public ABG9010_00_Door1Knob_Standard_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BG0029_00_Door1Knob_Standard_C">();
	}
	static class ABG0029_00_Door1Knob_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABG0029_00_Door1Knob_Standard_C>();
	}
};
static_assert(alignof(ABG0029_00_Door1Knob_Standard_C) == 0x000008, "Wrong alignment on ABG0029_00_Door1Knob_Standard_C");
static_assert(sizeof(ABG0029_00_Door1Knob_Standard_C) == 0x000810, "Wrong size on ABG0029_00_Door1Knob_Standard_C");

}

