#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: btsc_COMMON_VR

#include "Basic.hpp"

#include "btsc_COMMON_VR_classes.hpp"
#include "btsc_COMMON_VR_parameters.hpp"


namespace SDK
{

// Function btsc_COMMON_VR.btsc_COMMON_VR_C.ExecuteUbergraph_btsc_COMMON_VR
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_COMMON_VR_C::ExecuteUbergraph_btsc_COMMON_VR(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_COMMON_VR_C", "ExecuteUbergraph_btsc_COMMON_VR");

	Params::btsc_COMMON_VR_C_ExecuteUbergraph_btsc_COMMON_VR Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_COMMON_VR.btsc_COMMON_VR_C.OnEntryBattleScene
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             battleScenenBPName                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             territoryID                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_COMMON_VR_C::OnEntryBattleScene(const class FName& battleScenenBPName, const class FName& territoryID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_COMMON_VR_C", "OnEntryBattleScene");

	Params::btsc_COMMON_VR_C_OnEntryBattleScene Parms{};

	Parms.battleScenenBPName = battleScenenBPName;
	Parms.territoryID = territoryID;

	UObject::ProcessEvent(Func, &Parms);
}

}

