#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: btsc_2660_PCImmotality

#include "Basic.hpp"

#include "btsc_ptleader_Immotality_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass btsc_2660_PCImmotality.btsc_2660_PCImmotality_C
// 0x0000 (0x02D0 - 0x02D0)
class Abtsc_2660_PCImmotality_C final : public Abtsc_ptleader_Immotality_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"btsc_2660_PCImmotality_C">();
	}
	static class Abtsc_2660_PCImmotality_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abtsc_2660_PCImmotality_C>();
	}
};
static_assert(alignof(Abtsc_2660_PCImmotality_C) == 0x000008, "Wrong alignment on Abtsc_2660_PCImmotality_C");
static_assert(sizeof(Abtsc_2660_PCImmotality_C) == 0x0002D0, "Wrong size on Abtsc_2660_PCImmotality_C");

}

