#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Com_Loading

#include "Basic.hpp"


namespace SDK::Params
{

// Function Com_Loading.Com_Loading_C.ExecuteUbergraph_Com_Loading
// 0x0008 (0x0008 - 0x0000)
struct Com_Loading_C_ExecuteUbergraph_Com_Loading final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PlayAnimationByName_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Com_Loading_C_ExecuteUbergraph_Com_Loading) == 0x000004, "Wrong alignment on Com_Loading_C_ExecuteUbergraph_Com_Loading");
static_assert(sizeof(Com_Loading_C_ExecuteUbergraph_Com_Loading) == 0x000008, "Wrong size on Com_Loading_C_ExecuteUbergraph_Com_Loading");
static_assert(offsetof(Com_Loading_C_ExecuteUbergraph_Com_Loading, EntryPoint) == 0x000000, "Member 'Com_Loading_C_ExecuteUbergraph_Com_Loading::EntryPoint' has a wrong offset!");
static_assert(offsetof(Com_Loading_C_ExecuteUbergraph_Com_Loading, CallFunc_PlayAnimationByName_ReturnValue) == 0x000004, "Member 'Com_Loading_C_ExecuteUbergraph_Com_Loading::CallFunc_PlayAnimationByName_ReturnValue' has a wrong offset!");

}

