#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Command_Effect_00

#include "Basic.hpp"

#include "Command_Effect_00_classes.hpp"
#include "Command_Effect_00_parameters.hpp"


namespace SDK
{

// Function Command_Effect_00.Command_Effect_00_C.ExecuteUbergraph_Command_Effect_00
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommand_Effect_00_C::ExecuteUbergraph_Command_Effect_00(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Command_Effect_00_C", "ExecuteUbergraph_Command_Effect_00");

	Params::Command_Effect_00_C_ExecuteUbergraph_Command_Effect_00 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Command_Effect_00.Command_Effect_00_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCommand_Effect_00_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Command_Effect_00_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

