#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EB0016_00_Move_FastDash_ToPC

#include "Basic.hpp"

#include "Enemy_MoveDefBase_FastDash_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EB0016_00_Move_FastDash_ToPC.EB0016_00_Move_FastDash_ToPC_C
// 0x0000 (0x01A8 - 0x01A8)
class UEB0016_00_Move_FastDash_ToPC_C final : public UEnemy_MoveDefBase_FastDash_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EB0016_00_Move_FastDash_ToPC_C">();
	}
	static class UEB0016_00_Move_FastDash_ToPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEB0016_00_Move_FastDash_ToPC_C>();
	}
};
static_assert(alignof(UEB0016_00_Move_FastDash_ToPC_C) == 0x000008, "Wrong alignment on UEB0016_00_Move_FastDash_ToPC_C");
static_assert(sizeof(UEB0016_00_Move_FastDash_ToPC_C) == 0x0001A8, "Wrong size on UEB0016_00_Move_FastDash_ToPC_C");

}

