#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN0008_06_Move_Around

#include "Basic.hpp"

#include "EN0008_04_Move_Around_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EN0008_06_Move_Around.EN0008_06_Move_Around_C
// 0x0000 (0x00C8 - 0x00C8)
class UEN0008_06_Move_Around_C final : public UEN0008_04_Move_Around_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EN0008_06_Move_Around_C">();
	}
	static class UEN0008_06_Move_Around_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEN0008_06_Move_Around_C>();
	}
};
static_assert(alignof(UEN0008_06_Move_Around_C) == 0x000008, "Wrong alignment on UEN0008_06_Move_Around_C");
static_assert(sizeof(UEN0008_06_Move_Around_C) == 0x0000C8, "Wrong size on UEN0008_06_Move_Around_C");

}

