#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN0002_00_Move_ConfrontToAction

#include "Basic.hpp"

#include "Enemy_MoveDefBase_ConfrontToAction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EN0002_00_Move_ConfrontToAction.EN0002_00_Move_ConfrontToAction_C
// 0x0000 (0x00D0 - 0x00D0)
class UEN0002_00_Move_ConfrontToAction_C final : public UEnemy_MoveDefBase_ConfrontToAction_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EN0002_00_Move_ConfrontToAction_C">();
	}
	static class UEN0002_00_Move_ConfrontToAction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEN0002_00_Move_ConfrontToAction_C>();
	}
};
static_assert(alignof(UEN0002_00_Move_ConfrontToAction_C) == 0x000008, "Wrong alignment on UEN0002_00_Move_ConfrontToAction_C");
static_assert(sizeof(UEN0002_00_Move_ConfrontToAction_C) == 0x0000D0, "Wrong size on UEN0002_00_Move_ConfrontToAction_C");

}

