#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN2000_05_GuardHound_KalmFangEnd2_AIBP

#include "Basic.hpp"

#include "EN2000_05_GuardHound_KalmFangEnd2_AIBP_classes.hpp"
#include "EN2000_05_GuardHound_KalmFangEnd2_AIBP_parameters.hpp"


namespace SDK
{

// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.ExecuteUbergraph_EN2000_05_GuardHound_KalmFangEnd2_AIBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::ExecuteUbergraph_EN2000_05_GuardHound_KalmFangEnd2_AIBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "ExecuteUbergraph_EN2000_05_GuardHound_KalmFangEnd2_AIBP");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_ExecuteUbergraph_EN2000_05_GuardHound_KalmFangEnd2_AIBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnActionTopPriorityInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             TopPriorityActionId                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnActionTopPriorityInvoke(class FName TopPriorityActionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnActionTopPriorityInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnActionTopPriorityInvoke Parms{};

	Parms.TopPriorityActionId = TopPriorityActionId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.AsyncCheckConditionInvoke
// (Event, Protected, BlueprintEvent)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::AsyncCheckConditionInvoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "AsyncCheckConditionInvoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnProwlInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndAIProwlCallType                     CallType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnProwlInvoke(EEndAIProwlCallType CallType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnProwlInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnProwlInvoke Parms{};

	Parms.CallType = CallType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnTakeDamageInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InChara                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleAbilityCommandType            InCommandType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InGuard                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InBoneName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InAttributeWeak                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InDmgSrcID                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleAttributeType                 appendAttribute                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   justHitRotYaw                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          hitPosition                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InHeal                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InCounter                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FEndDataObjectBattleDamageSourceAccessordataObjectBattleDamageSource                           (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    useAbilityUCPC                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FEndDataObjectBattleAbilityAccessordataObjectBattleAbility                                (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnTakeDamageInvoke(int32 Damage, class AEndCharacter* InChara, class FName InName, EEndBattleAbilityCommandType InCommandType, bool InBind, bool InGuard, class FName InBoneName, bool InAttributeWeak, class FName InDmgSrcID, EEndBattleAttributeType appendAttribute, float justHitRotYaw, const struct FVector& hitPosition, bool InHeal, bool InCounter, const struct FEndDataObjectBattleDamageSourceAccessor& dataObjectBattleDamageSource, bool useAbilityUCPC, const struct FEndDataObjectBattleAbilityAccessor& dataObjectBattleAbility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnTakeDamageInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnTakeDamageInvoke Parms{};

	Parms.Damage = Damage;
	Parms.InChara = InChara;
	Parms.InName = InName;
	Parms.InCommandType = InCommandType;
	Parms.InBind = InBind;
	Parms.InGuard = InGuard;
	Parms.InBoneName = InBoneName;
	Parms.InAttributeWeak = InAttributeWeak;
	Parms.InDmgSrcID = InDmgSrcID;
	Parms.appendAttribute = appendAttribute;
	Parms.justHitRotYaw = justHitRotYaw;
	Parms.hitPosition = std::move(hitPosition);
	Parms.InHeal = InHeal;
	Parms.InCounter = InCounter;
	Parms.dataObjectBattleDamageSource = std::move(dataObjectBattleDamageSource);
	Parms.useAbilityUCPC = useAbilityUCPC;
	Parms.dataObjectBattleAbility = std::move(dataObjectBattleAbility);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnActionInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndAIIntervalType                      IntervalType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ExtraIntervalId                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnActionInvoke(EEndAIIntervalType IntervalType, class FName ExtraIntervalId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnActionInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnActionInvoke Parms{};

	Parms.IntervalType = IntervalType;
	Parms.ExtraIntervalId = ExtraIntervalId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnReactionSensingInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    CauserChara                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HandleId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleReactionNotificationType      NotificationType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleAttackDirectionType           AttackDirectionType                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnReactionSensingInvoke(class AEndCharacter* CauserChara, int32 HandleId, EEndBattleReactionNotificationType NotificationType, EEndBattleAttackDirectionType AttackDirectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnReactionSensingInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnReactionSensingInvoke Parms{};

	Parms.CauserChara = CauserChara;
	Parms.HandleId = HandleId;
	Parms.NotificationType = NotificationType;
	Parms.AttackDirectionType = AttackDirectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnMotionMessageInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnMotionMessageInvoke(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnMotionMessageInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnMotionMessageInvoke Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2000_05_GuardHound_KalmFangEnd2_AIBP.EN2000_05_GuardHound_KalmFangEnd2_AIBP_C.OnGiveDamageInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InGuard                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    KeepOver                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InCounter                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InBoneName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InAttributeWeak                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InDamageSourceID                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InSteal                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    heal                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    kill                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    justGuard                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bLock                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2000_05_GuardHound_KalmFangEnd2_AIBP_C::OnGiveDamageInvoke(int32 Damage, class AEndCharacter* InTarget, class FName InName, bool InBind, bool InGuard, bool KeepOver, bool InCounter, class FName InBoneName, bool InAttributeWeak, class FName InDamageSourceID, bool InSteal, bool heal, bool kill, bool justGuard, bool bLock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2000_05_GuardHound_KalmFangEnd2_AIBP_C", "OnGiveDamageInvoke");

	Params::EN2000_05_GuardHound_KalmFangEnd2_AIBP_C_OnGiveDamageInvoke Parms{};

	Parms.Damage = Damage;
	Parms.InTarget = InTarget;
	Parms.InName = InName;
	Parms.InBind = InBind;
	Parms.InGuard = InGuard;
	Parms.KeepOver = KeepOver;
	Parms.InCounter = InCounter;
	Parms.InBoneName = InBoneName;
	Parms.InAttributeWeak = InAttributeWeak;
	Parms.InDamageSourceID = InDamageSourceID;
	Parms.InSteal = InSteal;
	Parms.heal = heal;
	Parms.kill = kill;
	Parms.justGuard = justGuard;
	Parms.bLock = bLock;

	UObject::ProcessEvent(Func, &Parms);
}

}

