#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP

#include "Basic.hpp"

#include "EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_classes.hpp"
#include "EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_parameters.hpp"


namespace SDK
{

// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.ExecuteUbergraph_EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::ExecuteUbergraph_EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "ExecuteUbergraph_EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_ExecuteUbergraph_EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnShowPreloadedWaveReinforcement
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             reinforcementActorName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnShowPreloadedWaveReinforcement(class FName reinforcementActorName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnShowPreloadedWaveReinforcement");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnShowPreloadedWaveReinforcement Parms{};

	Parms.reinforcementActorName = reinforcementActorName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnMoveTimeOutInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndAIActionMoveTimeOut                 TimeOutType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             MoveDefTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ActionDefTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ComboDefTag                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnMoveTimeOutInvoke(EEndAIActionMoveTimeOut TimeOutType, class FName MoveDefTag, class FName ActionDefTag, class FName ComboDefTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnMoveTimeOutInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnMoveTimeOutInvoke Parms{};

	Parms.TimeOutType = TimeOutType;
	Parms.MoveDefTag = MoveDefTag;
	Parms.ActionDefTag = ActionDefTag;
	Parms.ComboDefTag = ComboDefTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnTakeDamagePhaseChangeHpLineInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Phase                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnTakeDamagePhaseChangeHpLineInvoke(int32 Phase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnTakeDamagePhaseChangeHpLineInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnTakeDamagePhaseChangeHpLineInvoke Parms{};

	Parms.Phase = Phase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnCreateDamageSource
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    InOwner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             DamageSourceID                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnCreateDamageSource(class AEndCharacter* InOwner, const class FName& DamageSourceID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnCreateDamageSource");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnCreateDamageSource Parms{};

	Parms.InOwner = InOwner;
	Parms.DamageSourceID = DamageSourceID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnChangeSyncActionState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             SyncActionID                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleSyncActionStateType           StateType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    targetChara                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             DetachDamageSourceID                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnChangeSyncActionState(const class FName& SyncActionID, EEndBattleSyncActionStateType StateType, class AEndCharacter* targetChara, const class FName& DetachDamageSourceID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnChangeSyncActionState");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnChangeSyncActionState Parms{};

	Parms.SyncActionID = SyncActionID;
	Parms.StateType = StateType;
	Parms.targetChara = targetChara;
	Parms.DetachDamageSourceID = DetachDamageSourceID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnReactionSensingInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    CauserChara                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HandleId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleReactionNotificationType      NotificationType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleAttackDirectionType           AttackDirectionType                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnReactionSensingInvoke(class AEndCharacter* CauserChara, int32 HandleId, EEndBattleReactionNotificationType NotificationType, EEndBattleAttackDirectionType AttackDirectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnReactionSensingInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnReactionSensingInvoke Parms{};

	Parms.CauserChara = CauserChara;
	Parms.HandleId = HandleId;
	Parms.NotificationType = NotificationType;
	Parms.AttackDirectionType = AttackDirectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnDestroyDamageSource
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             DamageSourceID                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Location                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FQuat                            Quat                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnDestroyDamageSource(const class FName& DamageSourceID, const struct FVector& Location, const struct FQuat& Quat)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnDestroyDamageSource");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnDestroyDamageSource Parms{};

	Parms.DamageSourceID = DamageSourceID;
	Parms.Location = std::move(Location);
	Parms.Quat = std::move(Quat);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnEndAbilityInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             AbilityId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    createdDamageSource                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    suspended                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    suspendedSummonCutScene                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnEndAbilityInvoke(class FName AbilityId, bool createdDamageSource, bool suspended, bool suspendedSummonCutScene)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnEndAbilityInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnEndAbilityInvoke Parms{};

	Parms.AbilityId = AbilityId;
	Parms.createdDamageSource = createdDamageSource;
	Parms.suspended = suspended;
	Parms.suspendedSummonCutScene = suspendedSummonCutScene;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnUseAbilityInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             AbilityId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnUseAbilityInvoke(class FName AbilityId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnUseAbilityInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnUseAbilityInvoke Parms{};

	Parms.AbilityId = AbilityId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnEndActionDefinitionInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             ActionDefTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             SuspendAbilityId                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bSuspendSummonCutScene                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnEndActionDefinitionInvoke(class FName ActionDefTag, class FName SuspendAbilityId, bool bSuspendSummonCutScene)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnEndActionDefinitionInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnEndActionDefinitionInvoke Parms{};

	Parms.ActionDefTag = ActionDefTag;
	Parms.SuspendAbilityId = SuspendAbilityId;
	Parms.bSuspendSummonCutScene = bSuspendSummonCutScene;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnEndBurst
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    instant                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnEndBurst(bool instant)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnEndBurst");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnEndBurst Parms{};

	Parms.instant = instant;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnBeginBurst
// (Event, Public, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnBeginBurst()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnBeginBurst");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnActionTopPriorityInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             TopPriorityActionId                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnActionTopPriorityInvoke(class FName TopPriorityActionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnActionTopPriorityInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnActionTopPriorityInvoke Parms{};

	Parms.TopPriorityActionId = TopPriorityActionId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.AsyncCheckConditionInvoke
// (Event, Protected, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::AsyncCheckConditionInvoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "AsyncCheckConditionInvoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnPartsBreak
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             PartsID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnPartsBreak(class FName PartsID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnPartsBreak");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnPartsBreak Parms{};

	Parms.PartsID = PartsID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnActionInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndAIIntervalType                      IntervalType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ExtraIntervalId                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnActionInvoke(EEndAIIntervalType IntervalType, class FName ExtraIntervalId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnActionInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnActionInvoke Parms{};

	Parms.IntervalType = IntervalType;
	Parms.ExtraIntervalId = ExtraIntervalId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnProwlInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndAIProwlCallType                     CallType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnProwlInvoke(EEndAIProwlCallType CallType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnProwlInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnProwlInvoke Parms{};

	Parms.CallType = CallType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnStartActionRestrictionInvoke
// (Event, Protected, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnStartActionRestrictionInvoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnStartActionRestrictionInvoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.Request Broken Destruction Tentacle
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::Request_Broken_Destruction_Tentacle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "Request Broken Destruction Tentacle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.Request Create Destruction Tentacle
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::Request_Create_Destruction_Tentacle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "Request Create Destruction Tentacle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.DestroyTentacleBladeDamagesource
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::DestroyTentacleBladeDamagesource()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "DestroyTentacleBladeDamagesource");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.SetVisivle
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::SetVisivle(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "SetVisivle");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_SetVisivle Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.GetBattleAllMemberChara
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::GetBattleAllMemberChara()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "GetBattleAllMemberChara");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.ChangeAttackInterval
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DeepMist                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::ChangeAttackInterval(bool DeepMist)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "ChangeAttackInterval");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_ChangeAttackInterval Parms{};

	Parms.DeepMist = DeepMist;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.CheckReinForcementLimit
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::CheckReinForcementLimit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "CheckReinForcementLimit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnDestroyDeepMist
// (BlueprintCallable, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnDestroyDeepMist()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnDestroyDeepMist");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnExtraConditionInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             ConditionTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnExtraConditionInvoke(class FName ConditionTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnExtraConditionInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnExtraConditionInvoke Parms{};

	Parms.ConditionTag = ConditionTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnAITimerInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnAITimerInvoke(class FName ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnAITimerInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnAITimerInvoke Parms{};

	Parms.ID = ID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnDead
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    AtBurst                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnDead(bool AtBurst)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnDead");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnDead Parms{};

	Parms.AtBurst = AtBurst;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnStartBattleInvoke
// (Event, Public, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnStartBattleInvoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnStartBattleInvoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnChangePhaseReadyInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   PrevPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NextPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnChangePhaseReadyInvoke(int32 PrevPhase, int32 NextPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnChangePhaseReadyInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnChangePhaseReadyInvoke Parms{};

	Parms.PrevPhase = PrevPhase;
	Parms.NextPhase = NextPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnChangePhaseFinishInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   PrevPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NextPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnChangePhaseFinishInvoke(int32 PrevPhase, int32 NextPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnChangePhaseFinishInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnChangePhaseFinishInvoke Parms{};

	Parms.PrevPhase = PrevPhase;
	Parms.NextPhase = NextPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnMotionStateMessageBegin
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InTotalDuration                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnMotionStateMessageBegin(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue, float InTotalDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnMotionStateMessageBegin");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnMotionStateMessageBegin Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;
	Parms.InTotalDuration = InTotalDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnMotionMessageInvoke
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnMotionMessageInvoke(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnMotionMessageInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnMotionMessageInvoke Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnDefinitionLockTargetInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             LockTargetTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnDefinitionLockTargetInvoke(class FName LockTargetTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnDefinitionLockTargetInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnDefinitionLockTargetInvoke Parms{};

	Parms.LockTargetTag = LockTargetTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnGroupMessageInvoke
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FEndAIBattleGroupNotifyInfo      NotifyInfo                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnGroupMessageInvoke(const struct FEndAIBattleGroupNotifyInfo& NotifyInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnGroupMessageInvoke");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_OnGroupMessageInvoke Parms{};

	Parms.NotifyInfo = std::move(NotifyInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnSummonCutSceneBegin
// (Event, Public, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnSummonCutSceneBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnSummonCutSceneBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.OnSummonCutSceneEnd
// (Event, Public, BlueprintEvent)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::OnSummonCutSceneEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "OnSummonCutSceneEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_R_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_R_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_R_K2Node_InputKeyEvent_0");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_R_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_O_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_O_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_O_K2Node_InputKeyEvent_1");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_O_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_Y_K2Node_InputKeyEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_Y_K2Node_InputKeyEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_Y_K2Node_InputKeyEvent_2");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_Y_K2Node_InputKeyEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_Z_K2Node_InputKeyEvent_3
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_Z_K2Node_InputKeyEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_Z_K2Node_InputKeyEvent_3");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_Z_K2Node_InputKeyEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_X_K2Node_InputKeyEvent_4
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_X_K2Node_InputKeyEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_X_K2Node_InputKeyEvent_4");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_X_K2Node_InputKeyEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_L_K2Node_InputKeyEvent_5
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_L_K2Node_InputKeyEvent_5(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_L_K2Node_InputKeyEvent_5");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_L_K2Node_InputKeyEvent_5 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_K_K2Node_InputKeyEvent_6
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_K_K2Node_InputKeyEvent_6(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_K_K2Node_InputKeyEvent_6");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_K_K2Node_InputKeyEvent_6 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_J_K2Node_InputKeyEvent_7
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_J_K2Node_InputKeyEvent_7(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_J_K2Node_InputKeyEvent_7");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_J_K2Node_InputKeyEvent_7 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_I_K2Node_InputKeyEvent_8
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_I_K2Node_InputKeyEvent_8(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_I_K2Node_InputKeyEvent_8");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_I_K2Node_InputKeyEvent_8 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_H_K2Node_InputKeyEvent_9
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_H_K2Node_InputKeyEvent_9(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_H_K2Node_InputKeyEvent_9");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_H_K2Node_InputKeyEvent_9 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_G_K2Node_InputKeyEvent_10
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_G_K2Node_InputKeyEvent_10(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_G_K2Node_InputKeyEvent_10");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_G_K2Node_InputKeyEvent_10 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_F_K2Node_InputKeyEvent_11
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_F_K2Node_InputKeyEvent_11(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_F_K2Node_InputKeyEvent_11");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_F_K2Node_InputKeyEvent_11 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_E_K2Node_InputKeyEvent_12
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_E_K2Node_InputKeyEvent_12(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_E_K2Node_InputKeyEvent_12");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_E_K2Node_InputKeyEvent_12 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_D_K2Node_InputKeyEvent_13
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_D_K2Node_InputKeyEvent_13(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_D_K2Node_InputKeyEvent_13");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_D_K2Node_InputKeyEvent_13 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_C_K2Node_InputKeyEvent_14
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_C_K2Node_InputKeyEvent_14(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_C_K2Node_InputKeyEvent_14");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_C_K2Node_InputKeyEvent_14 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_B_K2Node_InputKeyEvent_15
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_B_K2Node_InputKeyEvent_15(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_B_K2Node_InputKeyEvent_15");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_B_K2Node_InputKeyEvent_15 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_A_K2Node_InputKeyEvent_16
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_A_K2Node_InputKeyEvent_16(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_A_K2Node_InputKeyEvent_16");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_A_K2Node_InputKeyEvent_16 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_One_K2Node_InputKeyEvent_17
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_One_K2Node_InputKeyEvent_17(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_One_K2Node_InputKeyEvent_17");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_One_K2Node_InputKeyEvent_17 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_Two_K2Node_InputKeyEvent_18
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_Two_K2Node_InputKeyEvent_18(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_Two_K2Node_InputKeyEvent_18");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_Two_K2Node_InputKeyEvent_18 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.InpActEvt_Q_K2Node_InputKeyEvent_19
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::InpActEvt_Q_K2Node_InputKeyEvent_19(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "InpActEvt_Q_K2Node_InputKeyEvent_19");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_InpActEvt_Q_K2Node_InputKeyEvent_19 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP.EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C.Set Warp Progress
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SuccessRequest                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C::Set_Warp_Progress(bool* SuccessRequest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C", "Set Warp Progress");

	Params::EN2101_05_HereticRayleigh_SubspeciesEnd2_AIBP_C_Set_Warp_Progress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SuccessRequest != nullptr)
		*SuccessRequest = Parms.SuccessRequest;
}

}

