#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EndSwitchBase

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EndSwitchBase.EndSwitchBase_C
// 0x0000 (0x0C70 - 0x0C70)
class AEndSwitchBase_C : public AEndFieldActionSwitchAccessActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EndSwitchBase_C">();
	}
	static class AEndSwitchBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEndSwitchBase_C>();
	}
};
static_assert(alignof(AEndSwitchBase_C) == 0x000010, "Wrong alignment on AEndSwitchBase_C");
static_assert(sizeof(AEndSwitchBase_C) == 0x000C70, "Wrong size on AEndSwitchBase_C");

}

