#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventProgress_Parts_02

#include "Basic.hpp"

#include "EventProgress_Parts_02_classes.hpp"
#include "EventProgress_Parts_02_parameters.hpp"


namespace SDK
{

// Function EventProgress_Parts_02.EventProgress_Parts_02_C.ExecuteUbergraph_EventProgress_Parts_02
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEventProgress_Parts_02_C::ExecuteUbergraph_EventProgress_Parts_02(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EventProgress_Parts_02_C", "ExecuteUbergraph_EventProgress_Parts_02");

	Params::EventProgress_Parts_02_C_ExecuteUbergraph_EventProgress_Parts_02 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EventProgress_Parts_02.EventProgress_Parts_02_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UEventProgress_Parts_02_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EventProgress_Parts_02_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

