#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FA2003_00_FieldMaterialGras03_Standard

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FA2003_00_FieldMaterialGras03_Standard.FA2003_00_FieldMaterialGras03_Standard_C
// 0x0000 (0x0740 - 0x0740)
class AFA2003_00_FieldMaterialGras03_Standard_C final : public AEndSkeletalMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FA2003_00_FieldMaterialGras03_Standard_C">();
	}
	static class AFA2003_00_FieldMaterialGras03_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFA2003_00_FieldMaterialGras03_Standard_C>();
	}
};
static_assert(alignof(AFA2003_00_FieldMaterialGras03_Standard_C) == 0x000008, "Wrong alignment on AFA2003_00_FieldMaterialGras03_Standard_C");
static_assert(sizeof(AFA2003_00_FieldMaterialGras03_Standard_C) == 0x000740, "Wrong size on AFA2003_00_FieldMaterialGras03_Standard_C");

}

