#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FieldTarget_01

#include "Basic.hpp"


namespace SDK::Params
{

// Function FieldTarget_01.FieldTarget_01_C.ExecuteUbergraph_FieldTarget_01
// 0x0004 (0x0004 - 0x0000)
struct FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01) == 0x000004, "Wrong alignment on FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01");
static_assert(sizeof(FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01) == 0x000004, "Wrong size on FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01");
static_assert(offsetof(FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01, EntryPoint) == 0x000000, "Member 'FieldTarget_01_C_ExecuteUbergraph_FieldTarget_01::EntryPoint' has a wrong offset!");

}

