#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_WeaponUpgrade_SkilIcon

#include "Basic.hpp"

#include "MainMenu_WeaponUpgrade_SkilIcon_classes.hpp"
#include "MainMenu_WeaponUpgrade_SkilIcon_parameters.hpp"


namespace SDK
{

// Function MainMenu_WeaponUpgrade_SkilIcon.MainMenu_WeaponUpgrade_SkilIcon_C.ExecuteUbergraph_MainMenu_WeaponUpgrade_SkilIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_WeaponUpgrade_SkilIcon_C::ExecuteUbergraph_MainMenu_WeaponUpgrade_SkilIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_WeaponUpgrade_SkilIcon_C", "ExecuteUbergraph_MainMenu_WeaponUpgrade_SkilIcon");

	Params::MainMenu_WeaponUpgrade_SkilIcon_C_ExecuteUbergraph_MainMenu_WeaponUpgrade_SkilIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_WeaponUpgrade_SkilIcon.MainMenu_WeaponUpgrade_SkilIcon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_WeaponUpgrade_SkilIcon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_WeaponUpgrade_SkilIcon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

