#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_ItemTop

#include "Basic.hpp"

#include "MainMenu_ItemTop_classes.hpp"
#include "MainMenu_ItemTop_parameters.hpp"


namespace SDK
{

// Function MainMenu_ItemTop.MainMenu_ItemTop_C.ExecuteUbergraph_MainMenu_ItemTop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_ItemTop_C::ExecuteUbergraph_MainMenu_ItemTop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_ItemTop_C", "ExecuteUbergraph_MainMenu_ItemTop");

	Params::MainMenu_ItemTop_C_ExecuteUbergraph_MainMenu_ItemTop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_ItemTop.MainMenu_ItemTop_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_ItemTop_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_ItemTop_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

