#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: obm1350_aljunon_570_JNONT_Single_LookUpMan01

#include "Basic.hpp"

#include "obm1350_aljunon_570_JNONT_Single_LookUpMan01_classes.hpp"
#include "obm1350_aljunon_570_JNONT_Single_LookUpMan01_parameters.hpp"


namespace SDK
{

// Function obm1350_aljunon_570_JNONT_Single_LookUpMan01.obm1350_aljunon_570_JNONT_Single_LookUpMan01_C.CreateMobCommand
// (Event, Public, BlueprintEvent)

void Aobm1350_aljunon_570_JNONT_Single_LookUpMan01_C::CreateMobCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("obm1350_aljunon_570_JNONT_Single_LookUpMan01_C", "CreateMobCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function obm1350_aljunon_570_JNONT_Single_LookUpMan01.obm1350_aljunon_570_JNONT_Single_LookUpMan01_C.ExecuteUbergraph_obm1350_aljunon_570_JNONT_Single_LookUpMan01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aobm1350_aljunon_570_JNONT_Single_LookUpMan01_C::ExecuteUbergraph_obm1350_aljunon_570_JNONT_Single_LookUpMan01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("obm1350_aljunon_570_JNONT_Single_LookUpMan01_C", "ExecuteUbergraph_obm1350_aljunon_570_JNONT_Single_LookUpMan01");

	Params::obm1350_aljunon_570_JNONT_Single_LookUpMan01_C_ExecuteUbergraph_obm1350_aljunon_570_JNONT_Single_LookUpMan01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

