#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: obm1350_aljunon_1680_JNONT_Single_StudySoldier01

#include "Basic.hpp"

#include "MobPrefabTemplate_ReactionAndContact_01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass obm1350_aljunon_1680_JNONT_Single_StudySoldier01.obm1350_aljunon_1680_JNONT_Single_StudySoldier01_C
// 0x0000 (0x0790 - 0x0790)
class Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C final : public AMobPrefabTemplate_ReactionAndContact_01_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"obm1350_aljunon_1680_JNONT_Single_StudySoldier01_C">();
	}
	static class Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C>();
	}
};
static_assert(alignof(Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C) == 0x000010, "Wrong alignment on Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C");
static_assert(sizeof(Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C) == 0x000790, "Wrong size on Aobm1350_aljunon_1680_JNONT_Single_StudySoldier01_C");

}

