#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: obm1300_SquareArea_270_JUNOA_Double_Condor01

#include "Basic.hpp"

#include "obm1300_SquareArea_270_JUNOA_Double_Condor01_classes.hpp"
#include "obm1300_SquareArea_270_JUNOA_Double_Condor01_parameters.hpp"


namespace SDK
{

// Function obm1300_SquareArea_270_JUNOA_Double_Condor01.obm1300_SquareArea_270_JUNOA_Double_Condor01_C.ExecuteUbergraph_obm1300_SquareArea_270_JUNOA_Double_Condor01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aobm1300_SquareArea_270_JUNOA_Double_Condor01_C::ExecuteUbergraph_obm1300_SquareArea_270_JUNOA_Double_Condor01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("obm1300_SquareArea_270_JUNOA_Double_Condor01_C", "ExecuteUbergraph_obm1300_SquareArea_270_JUNOA_Double_Condor01");

	Params::obm1300_SquareArea_270_JUNOA_Double_Condor01_C_ExecuteUbergraph_obm1300_SquareArea_270_JUNOA_Double_Condor01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function obm1300_SquareArea_270_JUNOA_Double_Condor01.obm1300_SquareArea_270_JUNOA_Double_Condor01_C.CreateMobCommand
// (Event, Public, BlueprintEvent)

void Aobm1300_SquareArea_270_JUNOA_Double_Condor01_C::CreateMobCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("obm1300_SquareArea_270_JUNOA_Double_Condor01_C", "CreateMobCommand");

	UObject::ProcessEvent(Func, nullptr);
}

}

