#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: obm2100_GymArea_210_COSTA_Single_Squat05

#include "Basic.hpp"

#include "MobPrefabTemplate_LookAtAndContact_01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass obm2100_GymArea_210_COSTA_Single_Squat05.obm2100_GymArea_210_COSTA_Single_Squat05_C
// 0x0000 (0x0750 - 0x0750)
class Aobm2100_GymArea_210_COSTA_Single_Squat05_C final : public AMobPrefabTemplate_LookAtAndContact_01_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"obm2100_GymArea_210_COSTA_Single_Squat05_C">();
	}
	static class Aobm2100_GymArea_210_COSTA_Single_Squat05_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aobm2100_GymArea_210_COSTA_Single_Squat05_C>();
	}
};
static_assert(alignof(Aobm2100_GymArea_210_COSTA_Single_Squat05_C) == 0x000010, "Wrong alignment on Aobm2100_GymArea_210_COSTA_Single_Squat05_C");
static_assert(sizeof(Aobm2100_GymArea_210_COSTA_Single_Squat05_C) == 0x000750, "Wrong size on Aobm2100_GymArea_210_COSTA_Single_Squat05_C");

}

