#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: obm2660_FireDead_030_NIBLT_Single_OnFireFallDown03

#include "Basic.hpp"

#include "MobPrefabBase01_Single_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass obm2660_FireDead_030_NIBLT_Single_OnFireFallDown03.obm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C
// 0x0000 (0x0500 - 0x0500)
class Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C final : public AMobPrefabBase01_Single_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"obm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C">();
	}
	static class Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C>();
	}
};
static_assert(alignof(Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C) == 0x000010, "Wrong alignment on Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C");
static_assert(sizeof(Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C) == 0x000500, "Wrong size on Aobm2660_FireDead_030_NIBLT_Single_OnFireFallDown03_C");

}

