#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC0001_03_Barret_Sailor

#include "Basic.hpp"

#include "PC0001_00_Barret_Standard_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PC0001_03_Barret_Sailor.PC0001_03_Barret_Sailor_C
// 0x0000 (0x1890 - 0x1890)
class APC0001_03_Barret_Sailor_C final : public APC0001_00_Barret_Standard_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PC0001_03_Barret_Sailor_C">();
	}
	static class APC0001_03_Barret_Sailor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APC0001_03_Barret_Sailor_C>();
	}
};
static_assert(alignof(APC0001_03_Barret_Sailor_C) == 0x000010, "Wrong alignment on APC0001_03_Barret_Sailor_C");
static_assert(sizeof(APC0001_03_Barret_Sailor_C) == 0x001890, "Wrong size on APC0001_03_Barret_Sailor_C");

}

