#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shop_List_Item_Cell2

#include "Basic.hpp"


namespace SDK::Params
{

// Function Shop_List_Item_Cell2.Shop_List_Item_Cell2_C.ExecuteUbergraph_Shop_List_Item_Cell2
// 0x0004 (0x0004 - 0x0000)
struct Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2) == 0x000004, "Wrong alignment on Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2");
static_assert(sizeof(Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2) == 0x000004, "Wrong size on Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2");
static_assert(offsetof(Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2, EntryPoint) == 0x000000, "Member 'Shop_List_Item_Cell2_C_ExecuteUbergraph_Shop_List_Item_Cell2::EntryPoint' has a wrong offset!");

}

