#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shop_AreaChange_Stone

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Shop_AreaChange_Stone.Shop_AreaChange_Stone_C
// 0x0008 (0x03D0 - 0x03C8)
class UShop_AreaChange_Stone_C final : public UEndUserWidget
{
public:
	class UEndImageSet*                           Icon_Stone;                                        // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Shop_AreaChange_Stone_C">();
	}
	static class UShop_AreaChange_Stone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShop_AreaChange_Stone_C>();
	}
};
static_assert(alignof(UShop_AreaChange_Stone_C) == 0x000008, "Wrong alignment on UShop_AreaChange_Stone_C");
static_assert(sizeof(UShop_AreaChange_Stone_C) == 0x0003D0, "Wrong size on UShop_AreaChange_Stone_C");
static_assert(offsetof(UShop_AreaChange_Stone_C, Icon_Stone) == 0x0003C8, "Member 'UShop_AreaChange_Stone_C::Icon_Stone' has a wrong offset!");

}

