#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TalkLogs_Point

#include "Basic.hpp"

#include "TalkLogs_Point_classes.hpp"
#include "TalkLogs_Point_parameters.hpp"


namespace SDK
{

// Function TalkLogs_Point.TalkLogs_Point_C.ExecuteUbergraph_TalkLogs_Point
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTalkLogs_Point_C::ExecuteUbergraph_TalkLogs_Point(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TalkLogs_Point_C", "ExecuteUbergraph_TalkLogs_Point");

	Params::TalkLogs_Point_C_ExecuteUbergraph_TalkLogs_Point Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TalkLogs_Point.TalkLogs_Point_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTalkLogs_Point_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TalkLogs_Point_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

