#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TalkMenu_Cursor_00

#include "Basic.hpp"


namespace SDK::Params
{

// Function TalkMenu_Cursor_00.TalkMenu_Cursor_00_C.ExecuteUbergraph_TalkMenu_Cursor_00
// 0x0008 (0x0008 - 0x0000)
struct TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PlayAnimationByName_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00) == 0x000004, "Wrong alignment on TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00");
static_assert(sizeof(TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00) == 0x000008, "Wrong size on TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00");
static_assert(offsetof(TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00, EntryPoint) == 0x000000, "Member 'TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00::EntryPoint' has a wrong offset!");
static_assert(offsetof(TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00, CallFunc_PlayAnimationByName_ReturnValue) == 0x000004, "Member 'TalkMenu_Cursor_00_C_ExecuteUbergraph_TalkMenu_Cursor_00::CallFunc_PlayAnimationByName_ReturnValue' has a wrong offset!");

}

