#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VR_BattleTop

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VR_BattleTop.VR_BattleTop_C
// 0x0008 (0x03D0 - 0x03C8)
class UVR_BattleTop_C final : public UEndUserWidget
{
public:
	class UMiniGame_Com_CountDown_C*              CountDown;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VR_BattleTop_C">();
	}
	static class UVR_BattleTop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVR_BattleTop_C>();
	}
};
static_assert(alignof(UVR_BattleTop_C) == 0x000008, "Wrong alignment on UVR_BattleTop_C");
static_assert(sizeof(UVR_BattleTop_C) == 0x0003D0, "Wrong size on UVR_BattleTop_C");
static_assert(offsetof(UVR_BattleTop_C, CountDown) == 0x0003C8, "Member 'UVR_BattleTop_C::CountDown' has a wrong offset!");

}

