#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE0005_12_Yuffie_END2Weapon2

#include "Basic.hpp"

#include "WE0005_00_Yuffie_Shuriken_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WE0005_12_Yuffie_END2Weapon2.WE0005_12_Yuffie_END2Weapon2_C
// 0x0000 (0x0A10 - 0x0A10)
class AWE0005_12_Yuffie_END2Weapon2_C final : public AWE0005_00_Yuffie_Shuriken_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WE0005_12_Yuffie_END2Weapon2_C">();
	}
	static class AWE0005_12_Yuffie_END2Weapon2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWE0005_12_Yuffie_END2Weapon2_C>();
	}
};
static_assert(alignof(AWE0005_12_Yuffie_END2Weapon2_C) == 0x000010, "Wrong alignment on AWE0005_12_Yuffie_END2Weapon2_C");
static_assert(sizeof(AWE0005_12_Yuffie_END2Weapon2_C) == 0x000A10, "Wrong size on AWE0005_12_Yuffie_END2Weapon2_C");

}

