#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE1257_00_AerithSunglassWpn_Standard

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WE1257_00_AerithSunglassWpn_Standard.WE1257_00_AerithSunglassWpn_Standard_C
// 0x0000 (0x0A10 - 0x0A10)
class AWE1257_00_AerithSunglassWpn_Standard_C final : public AEndWeaponSkeletalMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WE1257_00_AerithSunglassWpn_Standard_C">();
	}
	static class AWE1257_00_AerithSunglassWpn_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWE1257_00_AerithSunglassWpn_Standard_C>();
	}
};
static_assert(alignof(AWE1257_00_AerithSunglassWpn_Standard_C) == 0x000010, "Wrong alignment on AWE1257_00_AerithSunglassWpn_Standard_C");
static_assert(sizeof(AWE1257_00_AerithSunglassWpn_Standard_C) == 0x000A10, "Wrong size on AWE1257_00_AerithSunglassWpn_Standard_C");

}

