#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero000_COMON_Layout_000_MenuTop

#include "Basic.hpp"

#include "Zero000_COMON_Layout_000_MenuTop_classes.hpp"
#include "Zero000_COMON_Layout_000_MenuTop_parameters.hpp"


namespace SDK
{

// Function 0000-COMON_Layout_000-MenuTop.0000-COMON_Layout_000-MenuTop_C.ExecuteUbergraph_0000-COMON_Layout_000-MenuTop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero000_COMON_Layout_000_MenuTop_C::ExecuteUbergraph_0000_COMON_Layout_000_MenuTop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("0000-COMON_Layout_000-MenuTop_C", "ExecuteUbergraph_0000-COMON_Layout_000-MenuTop");

	Params::Zero000_COMON_Layout_000_MenuTop_C_ExecuteUbergraph_0000_COMON_Layout_000_MenuTop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 0000-COMON_Layout_000-MenuTop.0000-COMON_Layout_000-MenuTop_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AZero000_COMON_Layout_000_MenuTop_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("0000-COMON_Layout_000-MenuTop_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

